### ISSUE TITLE
issue when write ng serve

### ISSUE THREAD

**Issue by mohammed-aladi** [bradtraversy/a4app#3]
I have problem that i can not run ng serve

i have got this :

$ ng serve
The "@angular/compiler-cli" package was not properly installed. Error: Error: Ca                                                                                                                                                                                               nnot find module '@angular/compiler'
Error: The "@angular/compiler-cli" package was not properly installed. Error: Er                                                                                                                                                                                               ror: Cannot find module '@angular/compiler'
    at Object.<anonymous> (C:\Users\mohammecd\AppData\Roaming\npm\node_modules\@                                                                                                                                                                                               angular\cli\node_modules\@ngtools\webpack\src\index.js:14:11)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\mohammecd\AppData\Roaming\npm\node_modules\@                                                                                                                                                                                               angular\cli\tasks\eject.js:10:19)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)

**Comment by nachogarrone** [comment]
you have to install dependencies.
Run: `npm install`
